
pimcore:
    objects:
        class_definitions:
            data:
                map:
                    manyToOneRelationSelect: \RelationSelectFieldsBundle\Model\Object\Data\ManyToOneRelationSelect
                    manyToManyRelationSelect: \RelationSelectFieldsBundle\Model\Object\Data\ManyToManyRelationSelect
    documents:
        tags:
            map:
                relation_select: \RelationSelectFieldsBundle\Model\Document\Tag\ManyToOneRelationSelect
                relations_select: \RelationSelectFieldsBundle\Model\Document\Tag\ManyToManyRelationSelect
